# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Polymer Games
email: info@polymergames.com
description: > # this means to ignore newlines until "baseurl:"
  Polymer Games is an indie game studio that makes game engine technology and mobile games.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://polymergames.com" # the base hostname & protocol for your site
twitter_username: polymer_games

# Build settings
markdown: kramdown

# Post settings
excerpt_separator: <!--more-->
