# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Polymer Games
email: info@polymergames.com
description: > # this means to ignore newlines until "baseurl:"
  In an industry full of innovative graphics and story-telling, our only goal is to make fun games. 
  Some of our favorites are Snake, Nokia's Space Impact, and the original Legend of Zelda.
  Our mission is to bring back the addictive gameplay of those classics on modern platforms.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://polymergames.com" # the base hostname & protocol for your site
twitter_username: polymer_games
facebook_username: polymergames
youtube_id: UCUzUuUaNOR_iE30HoBeky7Q

# Build settings
markdown: kramdown

# Post settings
excerpt_separator: <!--more-->
